# Generated by Django 4.2.11 on 2024-03-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='article_image',
            field=models.FileField(upload_to='article_images', verbose_name='Изображение'),
        ),
    ]
